### ISSUE TITLE
.dao domains search instead of resolve

### ISSUE THREAD

**Issue by rebelcode-xr** [unstoppabledomains/resolution-browser-extension#29]
When I try to open a .dao domain I get a web search instead of resolving it...maybe it happens also with other domains tlds, I don't know any domain connected to a website to test.

**Comment by DancingAxolotl** [comment]
@rebelcode-xr Thanks for reaching out! Unfortunately, I couldn't reproduce the issue. Could you share the domain that you are using?

There is also a page with test domains for browser resolution in our documentation, you can try some of them
https://docs.unstoppabledomains.com/developer-toolkit/resolve-domains-browser/test-domains/
And the extension provides a list of domains where you can find some more domains to test
<img width="401" alt="Screenshot 2022-04-07 at 16 20 14" src="https://user-images.githubusercontent.com/5020980/162221933-40f2c0da-48a4-4457-9f15-53b83588a444.png">

**Comment by rebelcode-xr** [comment]
I found out the problem: I must put `http(s)://` before the domain! Unfortunately that's not very intuitive/user-friendly from an user perspective... 🤔 

Proposal:
Could you allow the extension to recognise the domains even without `http(s)://` ?

**Comment by enaqx** [comment]
It should work with protocol prefix and without for the latest extension version. Thanks!
