### ISSUE TITLE
Unstoppable extension for Firefox

### ISSUE THREAD

**Issue by grahamperrin** [unstoppabledomains/resolution-browser-extension#6]
I tried using [Chrome Store Foxified 3.4](https://github.com/Noitidart/Chrome-Store-Foxified/issues/138) to add the extension for Chromium to Firefox 75.0. 

It seems to progress no further than: 

> Validating…

![image](https://user-images.githubusercontent.com/192271/78472325-bca01f00-772f-11ea-950e-9df29dde1bb0.png)

Might there be an extension for Firefox?

**Comment by n1ghtshade** [comment]
I'd also like to see a Firefox extension. 
Apparently it's fairly trivial to convert, I'll try and see if I can help with this, but might be beyond me.

**Comment by JohnnyJumper** [comment]
@grahamperrin  @n1ghtshade  the firefox extension has been deployed and available right now. 

https://addons.mozilla.org/en-US/firefox/addon/unstoppable-extension/
