### ISSUE TITLE
Why does this need permission to alter *.google.com domains?

### ISSUE THREAD

**Issue by resynth1943** [unstoppabledomains/resolution-browser-extension#8]
Title says it all.

[Is there a reason why this is here?](https://github.com/unstoppabledomains/resolution-browser-extension/blob/19fd875c02be7de51dbe19577d212a220078194e/static/manifest.json#L37)

**Comment by JohnnyJumper** [comment]
This allows us to catch the google search query. 

Like this one https://www.google.com/search?source=hp&ei=9xQrX_iSH4-xtQaegYLQDA&q=brad.crypto
People who have google search as a default search engine won't need to put / at the end of the domain in address bar to visit the website. Even if they type brad.crypto and hit enter (this will lead them to google search which we catch, parse and redirect to the website instead)

**Comment by resynth1943** [comment]
Yikes. Would you consider supporting other engines, like searX, DuckDuckGo, Mojeek, Qwant, Startpage? I'm probably forgetting some. Would you be happy for me to send a merge request?

**Comment by resynth1943** [comment]
Also, you really need to consider adding that explainer somewhere. Perhaps on the README?

To be honest, the first time I saw it, I thought it was some sort of shady redirection thing. Turns out it's not, but it would be better to explain beforehand.

**Comment by JohnnyJumper** [comment]
It would be amazing to have it done in a vendor-agnostic way. 
This can be a good feature to implement, contributions are always welcome! 
Would you care to try to make the PR?

**Comment by resynth1943** [comment]
I'll send in two PR's.

**Comment by JohnnyJumper** [comment]
In case you are working for a vendor-agnostic way. Here is an attempt to increase list of supported search engines #11

I am going to close the issue
Feel free to reopen this one or create a new one
